import mysql from 'mysql2/promise';
import pg from 'pg';
import mssql from 'mssql';

/**
 * Unified Database Adapter
 * Wraps different database drivers (MySQL, PostgreSQL, MSSQL) into a common interface.
 */
export class DatabaseAdapter {
    static async createAdapter(config) {
        let adapter;
        switch (config.type) {
            case 'mysql':
                adapter = new MySQLAdapter(config);
                break;
            case 'postgres':
            case 'pgsql':
                adapter = new PostgresAdapter(config);
                break;
            case 'mssql':
            case 'sqlserver':
                adapter = new MSSQLAdapter(config);
                break;
            default:
                throw new Error(`Unsupported database type: ${config.type}`);
        }
        await adapter.connect();
        return adapter;
    }
}

class BaseAdapter {
    constructor(config) {
        this.config = config;
    }
    async connect() { throw new Error("Not Implemented"); }
    async disconnect() { throw new Error("Not Implemented"); }
    async query(sql) { throw new Error("Not Implemented"); }
    async getTables() { throw new Error("Not Implemented"); }
    async getColumns(tableName) { throw new Error("Not Implemented"); }
}

// ==========================================
// MySQL Adapter
// ==========================================
class MySQLAdapter extends BaseAdapter {
    async connect() {
        this.connection = await mysql.createConnection({
            host: this.config.host,
            user: this.config.user,
            password: this.config.password,
            database: this.config.database,
            port: this.config.port || 3306,
            connectTimeout: 5000
        });
    }

    async disconnect() {
        if (this.connection) await this.connection.end();
    }

    async query(sql) {
        const [rows] = await this.connection.execute(sql);
        return rows;
    }

    async getTables() {
        const [rows] = await this.connection.execute("SHOW TABLES");
        return rows.map(r => Object.values(r)[0]);
    }

    async getColumns(tableName) {
        const [columns] = await this.connection.execute(`DESCRIBE ${tableName}`);
        // Map to standard format: { Field, Type, Key, Null }
        return columns.map(c => ({
            Field: c.Field,
            Type: c.Type,
            Key: c.Key,
            Null: c.Null
        }));
    }
}

// ==========================================
// PostgreSQL Adapter
// ==========================================
class PostgresAdapter extends BaseAdapter {
    async connect() {
        this.client = new pg.Client({
            host: this.config.host,
            user: this.config.user,
            password: this.config.password,
            database: this.config.database,
            port: this.config.port || 5432,
            ssl: this.config.ssl ? { rejectUnauthorized: false } : false
        });
        await this.client.connect();
    }

    async disconnect() {
        if (this.client) await this.client.end();
    }

    async query(sql) {
        // Postgres uses $1, $2 for params, but simple query strings work too.
        // However, standard SQL often uses " double quotes for identifiers in PG if mixed case.
        // For simplicity, we assume the SQL generated by LLM is compatible or we catch errors.
        const res = await this.client.query(sql);
        return res.rows;
    }

    async getTables() {
        const res = await this.client.query(`
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public'
        `);
        return res.rows.map(r => r.table_name);
    }

    async getColumns(tableName) {
        const res = await this.client.query(`
            SELECT column_name, data_type, is_nullable
            FROM information_schema.columns 
            WHERE table_name = '${tableName}'
        `);
        
        // Map to MySQL-like structure for compatibility with Profiler
        return res.rows.map(c => ({
            Field: c.column_name,
            Type: c.data_type,
            Key: '', // Constraints query is complex, skipping for basic profiling
            Null: c.is_nullable === 'YES' ? 'YES' : 'NO'
        }));
    }
}

// ==========================================
// MSSQL Adapter
// ==========================================
class MSSQLAdapter extends BaseAdapter {
    async connect() {
        this.pool = await mssql.connect({
            user: this.config.user,
            password: this.config.password,
            server: this.config.host,
            database: this.config.database,
            port: parseInt(this.config.port || 1433),
            options: {
                encrypt: true, // Use encryption by default for Azure compatibility
                trustServerCertificate: true // Self-signed certs
            }
        });
    }

    async disconnect() {
        if (this.pool) await this.pool.close();
    }

    async query(sql) {
        const result = await this.pool.request().query(sql);
        return result.recordset;
    }

    async getTables() {
        const result = await this.pool.request().query(`
            SELECT TABLE_NAME
            FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_TYPE = 'BASE TABLE'
        `);
        return result.recordset.map(r => r.TABLE_NAME);
    }

    async getColumns(tableName) {
        const result = await this.pool.request().query(`
            SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = '${tableName}'
        `);
        
        return result.recordset.map(c => ({
            Field: c.COLUMN_NAME,
            Type: c.DATA_TYPE,
            Key: '',
            Null: c.IS_NULLABLE
        }));
    }
}
